# Generated by Django 5.1.1 on 2025-07-05 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_course_management', '0001_initial'),
        ('a_institution_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('choice', 'Multiple Choice'), ('scale', 'Scale (1-10)')], max_length=10)),
                ('required', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
            },
        ),
        migrations.CreateModel(
            name='SurveyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'نظرسنجی آماده',
                'verbose_name_plural': 'نظرسنجی های آماده',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='a_survey_management.question')),
            ],
            options={
                'verbose_name': 'گزینه',
                'verbose_name_plural': 'گزینه ها',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='a_institution_management.branch')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='a_course_management.section')),
            ],
            options={
                'verbose_name': 'نظرسنجی',
                'verbose_name_plural': 'نظرسنجی ها',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='a_survey_management.survey'),
        ),
        migrations.CreateModel(
            name='TemplateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('choice', 'Multiple Choice'), ('scale', 'Scale (1-10)')], max_length=10)),
                ('required', models.BooleanField(default=True)),
                ('survey_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_questions', to='a_survey_management.surveytemplate')),
            ],
            options={
                'verbose_name': 'سوال آماده',
                'verbose_name_plural': 'سوالات آماده',
            },
        ),
        migrations.CreateModel(
            name='TemplateChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('template_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_choices', to='a_survey_management.templatequestion')),
            ],
            options={
                'verbose_name': 'گزینه آماده',
                'verbose_name_plural': 'گزینه های آماده',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_answer', models.IntegerField(blank=True, null=True)),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('section_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='a_course_management.sectionstudent')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_survey_management.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_survey_management.question')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ ها',
                'unique_together': {('section_student', 'question')},
            },
        ),
    ]
