# Generated by Django 5.1.1 on 2025-07-12 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0003_alter_degree_j_create_date_and_more'),
        ('a_survey_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_survey_management.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='section_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='a_course_management.sectionstudent'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choices', to='a_survey_management.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='a_survey_management.survey'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='a_course_management.section'),
        ),
        migrations.AlterField(
            model_name='templatechoice',
            name='template_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_choices', to='a_survey_management.templatequestion'),
        ),
        migrations.AlterField(
            model_name='templatequestion',
            name='survey_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_questions', to='a_survey_management.surveytemplate'),
        ),
    ]
