# Generated by Django 5.1.1 on 2024-12-03 03:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=63, null=True, verbose_name='عنوان')),
                ('transaction_id', models.CharField(blank=True, max_length=63, null=True, unique=True, verbose_name='شماره پیگیری')),
                ('formatted_amount', models.CharField(max_length=127, null=True, verbose_name='(تومان) مبلغ')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=11, null=True, verbose_name='(تومان) مبلغ')),
                ('created_method', models.CharField(choices=[('0', 'اتوماتیک'), ('1', 'دستی')], default='1', max_length=1, verbose_name='روش ثبت')),
                ('payment_method', models.CharField(choices=[('0', 'کارتخوان'), ('1', 'کارت به کارت'), ('2', 'نقدی'), ('3', 'درگاه پرداخت'), ('4', 'تخفیفی')], default='0', max_length=1, verbose_name='روش پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jdate', models.CharField(default='1403/09/13', max_length=15, verbose_name='تاریخ')),
                ('confirmed', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('description', models.TextField(blank=True, default='', max_length=511, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'رسید مالی',
                'verbose_name_plural': 'رسید های مالی',
                'ordering': ['confirmed', '-created_at'],
            },
        ),
    ]
