# Generated by Django 5.1.1 on 2024-10-17 00:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=63, null=True, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, max_length=511, null=True, verbose_name='توضیحات')),
                ('transaction_id', models.CharField(blank=True, max_length=63, null=True, unique=True, verbose_name='شماره پیگیری')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, null=True, verbose_name='(تومان) مبلغ')),
                ('sender_account', models.CharField(blank=True, max_length=63, null=True, verbose_name='ارسال شده از حساب')),
                ('receiver_account', models.CharField(blank=True, max_length=63, null=True, verbose_name='دریافت شده در حساب')),
                ('created_method', models.CharField(choices=[('0', 'اتوماتیک'), ('1', 'دستی')], default='1', max_length=1)),
                ('payment_method', models.CharField(choices=[('0', 'کارتخوان'), ('1', 'کارت به کارت'), ('2', 'نقدی'), ('3', 'درگاه پرداخت')], default='0', max_length=1, verbose_name='روش پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='پرداخت کننده')),
            ],
        ),
    ]
