# Generated by Django 5.1.1 on 2025-07-05 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_course_management', '0002_initial'),
        ('a_financial_management', '0001_initial'),
        ('a_user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='payer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='a_user_management.student', verbose_name='پرداخت کننده'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='a_course_management.section', verbose_name='دوره'),
        ),
    ]
