# Generated by Django 5.1.1 on 2024-10-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_financial_management', '0003_alter_receipt_jdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='jdate',
            field=models.CharField(default='1403/08/03', max_length=15, verbose_name='تاریخ'),
        ),
    ]
