# Generated by Django 5.1.1 on 2025-07-15 18:59

import a_financial_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_financial_management', '0003_alter_receipt_jdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='time_stamp',
            field=models.CharField(default=a_financial_management.models.generate_custom_id, editable=False, max_length=63),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='jdate',
            field=models.CharField(default='1404/04/24', max_length=15, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='reason',
            field=models.CharField(blank=True, choices=[('0', 'بابت قسط شهریه'), ('1', 'بابت شهریه'), ('2', 'بابت کلاس تقویتی'), ('3', 'بابت کمک به آموزشگاه'), ('4', 'بابت خسارت'), ('5', 'نامشخص'), ('6', 'پرداخت از کیف پول')], default='5', max_length=1, null=True, verbose_name='بابت'),
        ),
    ]
