# Generated by Django 5.1.1 on 2025-03-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_financial_management', '0003_receipt_reason_receipt_section_alter_receipt_jdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='jdate',
            field=models.CharField(default='1403/12/19', max_length=15, verbose_name='تاریخ'),
        ),
    ]
