# Generated by Django 5.1.1 on 2025-07-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_financial_management', '0004_receipt_time_stamp_alter_receipt_jdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='(تومان) مبلغ'),
        ),
    ]
