# Generated by Django 5.1.1 on 2024-11-04 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_financial_management', '0004_alter_receipt_jdate'),
        ('a_user_management', '0008_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='receiver_account',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='sender_account',
        ),
        migrations.AddField(
            model_name='receipt',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='jdate',
            field=models.CharField(default='1403/08/14', max_length=15, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_user_management.student', verbose_name='پرداخت کننده'),
        ),
    ]
