# Generated by Django 5.1.1 on 2024-11-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_financial_management', '0005_remove_receipt_receiver_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='formatted_amount',
            field=models.CharField(max_length=127, null=True, verbose_name='(تومان) مبلغ'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='jdate',
            field=models.CharField(default='1403/08/15', max_length=15, verbose_name='تاریخ'),
        ),
    ]
