# Generated by Django 5.1.1 on 2025-05-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_financial_management', '0006_alter_receipt_jdate'),
        ('a_institution_management', '0002_alter_branch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='a_institution_management.branch'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='jdate',
            field=models.CharField(default='1404/02/27', max_length=15, verbose_name='تاریخ'),
        ),
    ]
