# Generated by Django 5.1.1 on 2025-05-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_financial_management', '0007_receipt_branch_alter_receipt_jdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='jdate',
            field=models.CharField(default='1404/02/29', max_length=15, verbose_name='تاریخ'),
        ),
    ]
