# Generated by Django 5.1.1 on 2024-11-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_financial_management', '0007_alter_receipt_description_alter_receipt_jdate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['confirmed', '-created_at'], 'verbose_name': 'رسید مالی', 'verbose_name_plural': 'رسید های مالی'},
        ),
        migrations.AlterField(
            model_name='receipt',
            name='jdate',
            field=models.CharField(default='1403/08/30', max_length=15, verbose_name='تاریخ'),
        ),
    ]
