# Generated by Django 5.1.1 on 2025-05-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_institution_management', '0002_alter_branch_options'),
        ('a_notification_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='a_institution_management.branch'),
        ),
        migrations.AddField(
            model_name='notification',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='a_institution_management.branch'),
        ),
    ]
