# Generated by Django 5.1.1 on 2025-07-05 16:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_institution_management', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('code_melli', models.CharField(max_length=10, null=True, verbose_name='کد ملی')),
                ('phone', models.CharField(max_length=11, null=True, unique=True, verbose_name='تلفن همراه')),
                ('phone2', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='تلفن همراه 2')),
                ('date_of_birth', models.DateField(null=True, verbose_name='تاریخ تولد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='تصویر پروفایل')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, null=True)),
                ('gradeLevel', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'سطح',
                'verbose_name_plural': 'سطوح',
            },
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تاییدیه شماره',
                'verbose_name_plural': 'تاییدیه شماره ها',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مالک',
                'verbose_name_plural': '5- مالکان',
            },
            bases=('a_user_management.person',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='a_institution_management.branch')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': '3- کارمندان',
            },
            bases=('a_user_management.person',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='a_institution_management.branch')),
            ],
            options={
                'verbose_name': 'مدیر',
                'verbose_name_plural': '4- مدیران',
            },
            bases=('a_user_management.person',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.IntegerField(default=0, null=True, verbose_name='(تومان) مبلغ')),
                ('activity', models.CharField(choices=[('0', 'در حال تحصیل'), ('1', 'در انتظار ثبت نام'), ('2', 'معلق')], default=0, max_length=1, verbose_name='وضعیت')),
                ('education', models.CharField(choices=[('0', 'ابتدایی'), ('1', 'متوسطه اول'), ('2', 'متوسطه دوم'), ('3', 'دیپلم'), ('4', 'کاردانی'), ('5', 'کارشناسی'), ('6', 'کارشناسی ارشد'), ('7', 'دکتری')], max_length=1, null=True, verbose_name='تحصیلات')),
                ('ageLevel', models.CharField(choices=[('0', 'کودک'), ('1', 'نوجوان'), ('2', 'بزرگسال')], max_length=1, null=True, verbose_name='رده سنی')),
                ('gender', models.CharField(choices=[('0', 'پسر'), ('1', 'دختر')], max_length=1, null=True, verbose_name='جنسیت')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='a_institution_management.branch', verbose_name='شعبه')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='a_user_management.grade', verbose_name='سطح')),
            ],
            options={
                'verbose_name': 'دانشجو',
                'verbose_name_plural': '1- دانشجوها',
            },
            bases=('a_user_management.person',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='a_institution_management.branch')),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': '2- اساتید',
            },
            bases=('a_user_management.person',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
