# Generated by Django 5.1.1 on 2024-09-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
