# Generated by Django 5.1.1 on 2024-12-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'استاد', 'verbose_name_plural': '2- اساتید'},
        ),
    ]
