# Generated by Django 5.1.1 on 2024-09-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_user_management', '0002_alter_person_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='activity',
            field=models.CharField(choices=[('0', 'active'), ('1', 'ghost')], default=0, max_length=1),
        ),
    ]
