# Generated by Django 5.1.1 on 2024-09-29 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_user_management', '0003_student_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
    ]
