# Generated by Django 5.1.1 on 2024-10-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_user_management', '0003_alter_person_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_of_birth',
        ),
    ]
