# Generated by Django 5.1.1 on 2024-09-30 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_institution_management', '0001_initial'),
        ('a_user_management', '0004_alter_student_options_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='branch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='a_institution_management.branch'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='a_institution_management.institution'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='a_institution_management.branch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='a_institution_management.institution'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='title',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='institution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='a_institution_management.institution'),
        ),
        migrations.AlterField(
            model_name='person',
            name='code_melli',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='a_institution_management.branch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='a_user_management.grade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='a_institution_management.institution'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='a_institution_management.branch'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='a_institution_management.institution'),
        ),
    ]
