# Generated by Django 5.1.1 on 2024-10-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_user_management', '0005_person_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11, null=True, verbose_name='(تومان) مبلغ'),
        ),
    ]
