# Generated by Django 5.1.1 on 2024-11-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_user_management', '0007_alter_student_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('0', 'دخنر'), ('1', 'پسر')], max_length=1, null=True, verbose_name='جنسیت'),
        ),
    ]
