# Generated by Django 5.1.1 on 2024-11-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_user_management', '0008_student_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneverification',
            options={'verbose_name': 'تاییدیه شماره', 'verbose_name_plural': 'تاییدیه شماره ها'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='title',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='code_melli',
            field=models.CharField(max_length=10, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='student',
            name='activity',
            field=models.CharField(choices=[('0', 'در حال تحصیل'), ('1', 'در انتظار ثبت نام'), ('2', 'معلق')], default=0, max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ageLevel',
            field=models.CharField(choices=[('0', 'کودک'), ('1', 'نوجوان'), ('2', 'بزرگسال')], max_length=1, null=True, verbose_name='رده سنی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='education',
            field=models.CharField(choices=[('0', 'ابتدایی'), ('1', 'متوسطه اول'), ('2', 'متوسطه دوم'), ('3', 'دیپلم'), ('4', 'کاردانی'), ('5', 'کارشناسی'), ('6', 'کارشناسی ارشد'), ('7', 'دکتری')], max_length=1, null=True, verbose_name='تحصیلات'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('0', 'دخنر'), ('1', 'پسر')], max_length=1, null=True, verbose_name='جنسیت'),
        ),
    ]
