# Generated by Django 5.1.1 on 2024-10-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_user_management', '0008_remove_student_institution_student_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='randomCode',
        ),
        migrations.AddField(
            model_name='student',
            name='ageLevel',
            field=models.CharField(blank=True, choices=[('0', 'کودک'), ('1', 'نوجوان'), ('2', 'بزرگسال')], max_length=1, null=True),
        ),
    ]
