# Generated by Django 5.1.1 on 2024-11-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_user_management', '0009_alter_phoneverification_options_alter_grade_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('0', 'دختر'), ('1', 'پسر')], max_length=1, null=True, verbose_name='جنسیت'),
        ),
    ]
