# Generated by Django 5.1.1 on 2024-10-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_user_management', '0009_remove_person_randomcode_student_agelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skillLevel',
            field=models.CharField(blank=True, choices=[('0', 'مبتدی'), ('1', 'تعین سطح')], max_length=1, null=True),
        ),
    ]
