# Generated by Django 5.1.1 on 2024-11-19 23:07

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_institution_management', '0001_initial'),
        ('a_user_management', '0010_alter_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='a_institution_management.branch')),
            ],
            options={
                'verbose_name': 'مدیر',
                'verbose_name_plural': 'مدیران',
            },
            bases=('a_user_management.person',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
