# Generated by Django 5.1.1 on 2024-10-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_user_management', '0010_student_skilllevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'دانشجو', 'verbose_name_plural': 'دانشجو ها'},
        ),
    ]
