# Generated by Django 5.1.1 on 2024-12-03 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=63, null=True, verbose_name='تاریخ')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('grg_date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('session', models.CharField(blank=True, default='جلسه 1', max_length=31, null=True, verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'حضور غیاب ها',
                'verbose_name_plural': '4- حضور غیاب',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_time', models.DateTimeField(verbose_name='تاریخ آزمون')),
            ],
            options={
                'verbose_name': 'آزمون',
                'verbose_name_plural': '8- آزمون ها',
            },
        ),
        migrations.CreateModel(
            name='ExamDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='homeWorks/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'پاسخ آزمون',
                'verbose_name_plural': '9- پاسخ آزمون ها',
            },
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=127, null=True, verbose_name='عنوان')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='GivenHomeWorks/files/', verbose_name='فایل پیوست')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('expire_time', models.DateTimeField(verbose_name='مهلت تحویل')),
                ('description', models.TextField(blank=True, max_length=2047, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'تمرین',
                'verbose_name_plural': '6- تمرین ها',
            },
        ),
        migrations.CreateModel(
            name='HomeWorkDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='HomeWorks/files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seen', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نمره')),
            ],
            options={
                'verbose_name': 'پاسخ تمرین',
                'verbose_name_plural': '7- پاسخ تمرین ها',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=63, null=True, verbose_name='گروه')),
                ('online_section', models.BooleanField(default=False, verbose_name='برگزاری آنلاین')),
                ('capacity', models.IntegerField(blank=True, default=1, null=True, verbose_name='ظرفیت')),
                ('section_status', models.CharField(choices=[('0', 'اتمام مهلت ثبت نام'), ('1', 'در حال ثبت نام')], default=1, max_length=1, verbose_name='وضعیت')),
                ('session_number', models.IntegerField(blank=True, default=0, null=True, verbose_name=' تعداد جلسات برگزار شده ')),
                ('gender', models.CharField(blank=True, choices=[('0', 'دخنر'), ('1', 'پسر'), ('2', 'مختلط')], max_length=1, null=True, verbose_name='جنسیت')),
                ('start_date', models.DateField(null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(null=True, verbose_name='تاریخ پایان')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': '3- گروه ها',
            },
        ),
        migrations.CreateModel(
            name='SectionStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('0', 'در حال تحصیل'), ('1', 'دوره پایان یافته | قبول'), ('2', 'دوره پایان یافته | مردود')], default=0, max_length=1, verbose_name='وضعیت دانشجو در این دوره')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('class_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نمره کلاسی')),
                ('exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نمره پایانی')),
            ],
            options={
                'verbose_name': 'دوره برای دانشجو',
                'verbose_name_plural': '1- اطلاعات تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='SectionTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('0', 'شنبه'), ('1', 'یکشنبه'), ('2', 'دوشنبه'), ('3', 'سه شنبه'), ('4', 'چهارشنبه'), ('5', 'پنجشنبه'), ('6', 'جمعه')], max_length=1, verbose_name='روز')),
                ('timeOfSection', models.CharField(max_length=127, null=True, verbose_name='زمان')),
                ('place', models.CharField(max_length=63, null=True, verbose_name='مکان')),
            ],
            options={
                'verbose_name': 'زمان سکشن',
                'verbose_name_plural': 'زمان سکشن ها',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='نام دوره')),
                ('course_img', models.ImageField(null=True, upload_to='Course_images/', verbose_name='تصویر دوره')),
                ('price', models.CharField(max_length=127, null=True, verbose_name='قیمت ثبت نام به تومان')),
                ('installment', models.CharField(blank=True, choices=[('0', 'ندارد'), ('1', 'دارد')], default=0, max_length=1, null=True, verbose_name='اقساط')),
                ('courseDuration', models.CharField(blank=True, max_length=63, null=True, verbose_name='تعداد جلسات دوره')),
                ('session_length', models.CharField(blank=True, max_length=63, null=True, verbose_name='مدت زمان هر جلسه')),
                ('course_hours', models.IntegerField(default=10, null=True, verbose_name='تعداد ساعت دوره')),
                ('description', models.TextField(blank=True, max_length=2047, null=True, verbose_name='توضیحات')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_for', to='a_course_management.course', verbose_name='پیشنیاز ها')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': '2- دوره ها',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='Degrees/', verbose_name='فایل پیوست مدرک')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_hours', models.IntegerField(default=10, null=True, verbose_name='تعداد ساعت دوره')),
                ('serial', models.CharField(max_length=127, null=True, verbose_name='شماره سریال')),
                ('j_create_date', models.CharField(default='1403/09/13', max_length=15, verbose_name='تاریخ صدور')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='a_course_management.course')),
            ],
            options={
                'verbose_name': 'مدرک',
                'verbose_name_plural': '5- مدارک',
            },
        ),
    ]
