# Generated by Django 5.1.1 on 2024-10-12 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_time', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
            options={
                'verbose_name': 'آزمون',
                'verbose_name_plural': ' آزمون ها',
            },
        ),
        migrations.CreateModel(
            name='ExamDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='homeWorks/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'پاسخ آزمون',
                'verbose_name_plural': 'پاسخ آزمون ها',
            },
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=127, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'تمرین',
                'verbose_name_plural': 'تمرین ها',
            },
        ),
        migrations.CreateModel(
            name='HomeWorkDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='homeWorks/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پاسخ تمرین',
                'verbose_name_plural': 'پاسخ تمرین ها',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=63, null=True)),
                ('capacity', models.IntegerField(blank=True, default=1, null=True)),
                ('registered', models.IntegerField(blank=True, default=0, null=True)),
                ('section_status', models.CharField(choices=[('0', 'اتمام مهلت ثبت نام'), ('1', 'در حال ثبت نام')], default=1, max_length=1)),
            ],
            options={
                'verbose_name': 'سکشن',
                'verbose_name_plural': 'سکشن ها',
            },
        ),
        migrations.CreateModel(
            name='SectionStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('SAT', 'شنبه'), ('SUN', 'یکشنبه'), ('MON', 'دوشنبه'), ('TUE', 'سه شنبه'), ('WED', 'چهارشنبه'), ('THU', 'پنجشنبه'), ('FRI', 'جمعه')], max_length=3)),
                ('timeOfSection', models.CharField(blank=True, max_length=127, null=True)),
                ('place', models.CharField(blank=True, max_length=63, null=True)),
            ],
            options={
                'verbose_name': 'زمان سکشن',
                'verbose_name_plural': 'زمان سکشن ها',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=2047, null=True)),
                ('course_img', models.ImageField(blank=True, null=True, upload_to='Course_images/')),
                ('price', models.CharField(blank=True, max_length=127, null=True)),
                ('installment', models.CharField(blank=True, choices=[('0', 'ندارد'), ('1', 'دارد')], default=0, max_length=1, null=True)),
                ('courseDuration', models.CharField(blank=True, max_length=127, null=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_for', to='a_course_management.course')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره ها',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='a_course_management.course')),
            ],
            options={
                'verbose_name': 'مدرک',
                'verbose_name_plural': 'مدارک',
            },
        ),
    ]
