# Generated by Django 5.1.1 on 2024-12-03 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_course_management', '0001_initial'),
        ('a_user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='a_user_management.student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='a_user_management.teacher', verbose_name='استاد'),
        ),
        migrations.AddField(
            model_name='examdocument',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='a_course_management.exam'),
        ),
        migrations.AddField(
            model_name='examdocument',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='a_user_management.student'),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='a_user_management.teacher', verbose_name='استاد'),
        ),
        migrations.AddField(
            model_name='homeworkdocument',
            name='homeWork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='a_course_management.homework', verbose_name='تمرین'),
        ),
        migrations.AddField(
            model_name='homeworkdocument',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeWorks', to='a_user_management.student', verbose_name='دانش آموزش'),
        ),
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='a_course_management.course', verbose_name='دوره'),
        ),
        migrations.AddField(
            model_name='section',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='a_user_management.teacher', verbose_name='استاد'),
        ),
        migrations.AddField(
            model_name='homework',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='a_course_management.section', verbose_name='گروه'),
        ),
        migrations.AddField(
            model_name='exam',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='a_course_management.section', verbose_name='گروه'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='a_course_management.section', verbose_name='سکشن'),
        ),
        migrations.AddField(
            model_name='sectionstudent',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_course_management.section', verbose_name='گروه'),
        ),
        migrations.AddField(
            model_name='sectionstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_student', to='a_user_management.student', verbose_name='دانشجو'),
        ),
        migrations.AddField(
            model_name='section',
            name='students',
            field=models.ManyToManyField(related_name='sections', through='a_course_management.SectionStudent', to='a_user_management.student', verbose_name='دانشجو ها'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='section_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='a_course_management.sectionstudent', verbose_name='دانشجو'),
        ),
        migrations.AddField(
            model_name='sectiontimeslot',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='a_course_management.section', verbose_name='گروه'),
        ),
        migrations.AlterUniqueTogether(
            name='degree',
            unique_together={('course', 'student')},
        ),
    ]
