# Generated by Django 5.1.1 on 2025-07-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='j_create_date',
            field=models.CharField(default='1404/04/21', max_length=15, verbose_name='تاریخ صدور'),
        ),
        migrations.AlterField(
            model_name='sectionstudent',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع'),
        ),
    ]
