# Generated by Django 5.1.1 on 2024-09-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0002_homework_homeworkdocument'),
        ('a_user_management', '0002_alter_person_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='a_user_management.student'),
        ),
    ]
