# Generated by Django 5.1.1 on 2024-12-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='section',
            name='start_date',
        ),
        migrations.AddField(
            model_name='sectionstudent',
            name='end_date',
            field=models.DateField(null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AddField(
            model_name='sectionstudent',
            name='start_date',
            field=models.DateField(null=True, verbose_name='تاریخ شروع'),
        ),
    ]
