# Generated by Django 5.1.1 on 2024-10-14 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0002_initial'),
        ('a_user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseDuration',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='مقدار جلسات دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(blank=True, null=True, upload_to='Course_images/', verbose_name='تصویر دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=2047, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='course',
            name='installment',
            field=models.CharField(blank=True, choices=[('0', 'ندارد'), ('1', 'دارد')], default=0, max_length=1, null=True, verbose_name='اقساط'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_for', to='a_course_management.course', verbose_name='پیشنیاز ها'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='قیمت ثبت نام'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام دوره'),
        ),
        migrations.AlterField(
            model_name='section',
            name='capacity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='a_course_management.course', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='section',
            name='registered',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ثبت نام شده'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_status',
            field=models.CharField(choices=[('0', 'اتمام مهلت ثبت نام'), ('1', 'در حال ثبت نام')], default=1, max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='section',
            name='students',
            field=models.ManyToManyField(related_name='sections', through='a_course_management.SectionStudent', to='a_user_management.student', verbose_name='دانشجو ها'),
        ),
        migrations.AlterField(
            model_name='section',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='a_user_management.teacher', verbose_name='استاد'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('section_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_course_management.sectionstudent')),
            ],
            options={
                'unique_together': {('section_student', 'date')},
            },
        ),
    ]
