# Generated by Django 5.1.1 on 2025-07-15 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0003_alter_degree_j_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionstudent',
            name='dept',
            field=models.IntegerField(default=0, null=True, verbose_name='(تومان) مانده بدهی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0, null=True, verbose_name='(تومان)  قیمت'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='j_create_date',
            field=models.CharField(default='1404/04/24', max_length=15, verbose_name='تاریخ صدور'),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='a_course_management.course', verbose_name='دوره'),
        ),
    ]
