# Generated by Django 5.1.1 on 2025-07-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0004_sectionstudent_dept_alter_course_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionstudent',
            name='dept',
            field=models.IntegerField(blank=True, null=True, verbose_name='(تومان) مانده بدهی'),
        ),
    ]
