# Generated by Django 5.1.1 on 2024-10-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0004_remove_course_students_remove_course_teachers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseDuration',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='installment',
            field=models.CharField(blank=True, choices=[('0', 'ندارد'), ('1', 'دارد')], default=0, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='sectiontimeslot',
            name='place',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
