# Generated by Django 5.1.1 on 2024-10-14 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0004_attendance_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'حضور غیاب ها', 'verbose_name_plural': 'حضور غیاب'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='a_course_management.section', verbose_name='سکشن'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='section_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_course_management.sectionstudent', verbose_name='دانشجو'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(default=False, verbose_name='وضعیت'),
        ),
    ]
