# Generated by Django 5.1.1 on 2024-12-24 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0004_alter_sectionstudent_end_date_and_more'),
        ('a_user_management', '0002_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='a_course_management.section', verbose_name='سکشن'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='section_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='a_course_management.sectionstudent', verbose_name='دانشجو'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degrees', to='a_course_management.course'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='j_create_date',
            field=models.CharField(default='1403/10/04', max_length=15, verbose_name='تاریخ صدور'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degrees', to='a_user_management.student'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam', to='a_course_management.section', verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='a_user_management.teacher', verbose_name='استاد'),
        ),
        migrations.AlterField(
            model_name='examdocument',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='a_course_management.exam'),
        ),
        migrations.AlterField(
            model_name='examdocument',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='a_user_management.student'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='a_course_management.section', verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='a_user_management.teacher', verbose_name='استاد'),
        ),
        migrations.AlterField(
            model_name='homeworkdocument',
            name='homeWork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='a_course_management.homework', verbose_name='تمرین'),
        ),
        migrations.AlterField(
            model_name='homeworkdocument',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeWorks', to='a_user_management.student', verbose_name='دانش آموزش'),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='a_course_management.course', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='section',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='a_user_management.teacher', verbose_name='استاد'),
        ),
        migrations.AlterField(
            model_name='sectionstudent',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_students', to='a_course_management.section', verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='sectionstudent',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_students', to='a_user_management.student', verbose_name='دانشجو'),
        ),
        migrations.AlterField(
            model_name='sectiontimeslot',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_slots', to='a_course_management.section', verbose_name='گروه'),
        ),
    ]
