# Generated by Django 5.1.1 on 2025-03-09 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0005_alter_attendance_section_and_more'),
        ('a_user_management', '0002_alter_teacher_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degrees', to='a_user_management.teacher', verbose_name='استاد'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='j_create_date',
            field=models.CharField(default='1403/12/19', max_length=15, verbose_name='تاریخ صدور'),
        ),
    ]
