# Generated by Django 5.1.1 on 2024-10-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0006_degree_examdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
