# Generated by Django 5.1.1 on 2025-03-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0006_degree_teacher_alter_degree_j_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='online_section',
        ),
        migrations.AddField(
            model_name='section',
            name='method',
            field=models.CharField(default='0', max_length=1, verbose_name='نحوه برگزاری'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='j_create_date',
            field=models.CharField(default='1404/01/08', max_length=15, verbose_name='تاریخ صدور'),
        ),
    ]
