# Generated by Django 5.1.1 on 2024-10-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0007_attendance_grg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.CharField(blank=True, default='جلسه 1', max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='session_number',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name=' تعداد جلسات برگزار شده '),
        ),
    ]
