# Generated by Django 5.1.1 on 2025-05-10 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0007_remove_section_online_section_section_method_and_more'),
        ('a_institution_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='a_institution_management.branch'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='j_create_date',
            field=models.CharField(default='1404/02/20', max_length=15, verbose_name='تاریخ صدور'),
        ),
        migrations.AlterField(
            model_name='section',
            name='method',
            field=models.CharField(choices=[('0', 'حضوری'), ('1', 'آنلاین')], default=0, max_length=1, verbose_name='نحوه برگزاری'),
        ),
    ]
