# Generated by Django 5.1.1 on 2025-05-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0008_course_branch_alter_degree_j_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(blank=True, null=True, upload_to='Course_images/', verbose_name='تصویر دوره'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='j_create_date',
            field=models.CharField(default='1404/02/27', max_length=15, verbose_name='تاریخ صدور'),
        ),
    ]
