# Generated by Django 5.1.1 on 2025-05-19 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0009_alter_course_course_img_alter_degree_j_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('choice', 'Multiple Choice'), ('scale', 'Scale (1-10)')], max_length=10)),
                ('required', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='degree',
            name='j_create_date',
            field=models.CharField(default='1404/02/29', max_length=15, verbose_name='تاریخ صدور'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='a_course_management.question')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='a_course_management.section')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='a_course_management.survey'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_answer', models.IntegerField(blank=True, null=True)),
                ('section_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='a_course_management.sectionstudent')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_course_management.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_course_management.question')),
            ],
            options={
                'unique_together': {('section_student', 'question')},
            },
        ),
    ]
