# Generated by Django 5.1.1 on 2024-10-15 20:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0009_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='duration',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='grg_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ'),
            preserve_default=False,
        ),
    ]
