# Generated by Django 5.1.1 on 2024-10-15 22:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0010_remove_exam_duration_alter_attendance_grg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='expire_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
