# Generated by Django 5.1.1 on 2025-05-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0010_question_alter_degree_j_create_date_choice_survey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='section',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
