# Generated by Django 5.1.1 on 2024-10-15 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0011_homework_expire_time'),
        ('a_user_management', '0005_person_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='description',
            field=models.TextField(blank=True, max_length=2047, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='homework',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='GivenHomeWorks/files/', verbose_name='فایل پیوست'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_time',
            field=models.DateTimeField(verbose_name='تاریخ آزمون'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='a_course_management.section', verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='expire_time',
            field=models.DateTimeField(verbose_name='مهلت تحویل'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='a_course_management.section', verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='a_user_management.teacher', verbose_name='استاد'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='homeworkdocument',
            name='pdf',
            field=models.FileField(upload_to='HomeWorks/files/'),
        ),
    ]
