# Generated by Django 5.1.1 on 2024-10-15 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0013_exam_teacher'),
        ('a_user_management', '0005_person_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionstudent',
            options={'verbose_name': 'ثبت نمرات پایانی', 'verbose_name_plural': 'ثبت نمرات پایانی'},
        ),
        migrations.AddField(
            model_name='homeworkdocument',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sectionstudent',
            name='activity',
            field=models.CharField(choices=[('0', 'در حال تحصیل'), ('1', 'پایان دوره')], default=0, max_length=1, verbose_name='وضعیت دانشجو در این دوره'),
        ),
        migrations.AddField(
            model_name='sectionstudent',
            name='class_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='نمره کلاسی'),
        ),
        migrations.AddField(
            model_name='sectionstudent',
            name='exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='نمره پایانی'),
        ),
        migrations.AlterField(
            model_name='sectionstudent',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_course_management.section', verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='sectionstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_user_management.student', verbose_name='دانشجو'),
        ),
    ]
