# Generated by Django 5.1.1 on 2024-10-17 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0015_homeworkdocument_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionstudent',
            options={'verbose_name': 'دوره برای دانشجو', 'verbose_name_plural': 'دوره های دانشجو ها'},
        ),
    ]
