# Generated by Django 5.1.1 on 2024-11-04 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0017_degree_pdf_alter_attendance_section_student_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sectiontimeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='course_hours',
            field=models.IntegerField(default=10, null=True, verbose_name='تعداد ساعت دوره'),
        ),
        migrations.AddField(
            model_name='degree',
            name='course_hours',
            field=models.IntegerField(default=10, null=True, verbose_name='تعداد ساعت دوره'),
        ),
        migrations.AddField(
            model_name='degree',
            name='j_create_date',
            field=models.CharField(default='1403/08/14', max_length=15, verbose_name='تاریخ صدور'),
        ),
        migrations.AddField(
            model_name='degree',
            name='serial',
            field=models.CharField(max_length=127, null=True, verbose_name='شماره سریال'),
        ),
        migrations.AddField(
            model_name='section',
            name='gender',
            field=models.CharField(blank=True, choices=[('0', 'دخنر'), ('1', 'پسر'), ('2', 'مختلط')], max_length=1, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(null=True, upload_to='Course_images/', verbose_name='تصویر دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='قیمت ثبت نام به تومان'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='نام دوره'),
        ),
        migrations.AlterField(
            model_name='sectiontimeslot',
            name='day_of_week',
            field=models.CharField(choices=[('0', 'شنبه'), ('1', 'یکشنبه'), ('2', 'دوشنبه'), ('3', 'سه شنبه'), ('4', 'چهارشنبه'), ('5', 'پنجشنبه'), ('6', 'جمعه')], max_length=1, verbose_name='روز'),
        ),
        migrations.AlterField(
            model_name='sectiontimeslot',
            name='place',
            field=models.CharField(max_length=63, null=True, verbose_name='مکان'),
        ),
        migrations.AlterField(
            model_name='sectiontimeslot',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='a_course_management.section', verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='sectiontimeslot',
            name='timeOfSection',
            field=models.CharField(max_length=127, null=True, verbose_name='زمان'),
        ),
    ]
