# Generated by Django 5.1.1 on 2024-11-17 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0019_alter_course_price_alter_degree_j_create_date'),
        ('a_user_management', '0009_alter_phoneverification_options_alter_grade_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='session_length',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='مدت زمان هر جلسه'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseDuration',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='مقدار جلسات دوره'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='j_create_date',
            field=models.CharField(default='1403/08/28', max_length=15, verbose_name='تاریخ صدور'),
        ),
        migrations.AlterField(
            model_name='homeworkdocument',
            name='homeWork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='a_course_management.homework', verbose_name='تمرین'),
        ),
        migrations.AlterField(
            model_name='homeworkdocument',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نمره'),
        ),
        migrations.AlterField(
            model_name='homeworkdocument',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='homeworkdocument',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeWorks', to='a_user_management.student', verbose_name='دانش آموزش'),
        ),
        migrations.AlterField(
            model_name='sectionstudent',
            name='activity',
            field=models.CharField(choices=[('0', 'در حال تحصیل'), ('1', 'دوره پایان یافته | قبول'), ('2', 'دوره پایان یافته | مردود')], default=0, max_length=1, verbose_name='وضعیت دانشجو در این دوره'),
        ),
        migrations.AlterField(
            model_name='sectionstudent',
            name='class_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='نمره کلاسی'),
        ),
        migrations.AlterField(
            model_name='sectionstudent',
            name='exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='نمره پایانی'),
        ),
    ]
