# Generated by Django 5.1.1 on 2024-11-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0020_course_session_length_alter_course_courseduration_and_more'),
        ('a_user_management', '0010_alter_student_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionstudent',
            options={'verbose_name': 'دوره برای دانشجو', 'verbose_name_plural': 'دانشجو های دوره'},
        ),
        migrations.AddField(
            model_name='section',
            name='end_date',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='پایان دوره'),
        ),
        migrations.AddField(
            model_name='section',
            name='online_section',
            field=models.BooleanField(default=False, verbose_name='برگزاری آنلاین'),
        ),
        migrations.AddField(
            model_name='section',
            name='start_date',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='شروع دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseDuration',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='تعداد جلسات دوره'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='j_create_date',
            field=models.CharField(default='1403/08/30', max_length=15, verbose_name='تاریخ صدور'),
        ),
        migrations.AlterField(
            model_name='sectionstudent',
            name='class_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نمره کلاسی'),
        ),
        migrations.AlterField(
            model_name='sectionstudent',
            name='exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نمره پایانی'),
        ),
        migrations.AlterUniqueTogether(
            name='degree',
            unique_together={('course', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='sectionstudent',
            unique_together={('section', 'student')},
        ),
    ]
