# Generated by Django 5.1.1 on 2024-11-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_course_management', '0021_alter_sectionstudent_options_section_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='end_date',
            field=models.DateField(null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='section',
            name='start_date',
            field=models.DateField(null=True, verbose_name='تاریخ شروع'),
        ),
    ]
