# Generated by Django 5.1.1 on 2025-05-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_institution_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'شعبه', 'verbose_name_plural': 'شعب'},
        ),
    ]
